name: pesotrack
description: "PesoTrack - diario de peso inteligente."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3
  path: ^1.9.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  google_mlkit_text_recognition: ^0.13.1
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  fl_chart: ^0.68.0
  http: ^1.2.1
  connectivity_plus: ^6.0.5
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  intl: ^0.20.2
  share_plus: ^9.0.0
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_base.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"
  adaptive_icon_background: "assets/icons/background.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
